# config/packages/security.yaml
security:
    password_hashers:
        App\Entity\User: auto
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        users_in_memory: { memory: null }
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: client_accueil
            logout:
                path: app_logout
                target: app_front_home
            custom_authenticators:
                - App\Security\GoogleAuthenticator

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/connect, roles: PUBLIC_ACCESS }
        - { path: ^/reset-password/.*, roles: PUBLIC_ACCESS }
        - { path: ^/forgot-password, roles: PUBLIC_ACCESS }
        - { path: ^/verify-code, roles: PUBLIC_ACCESS }
        - { path: ^/reset-password-form, roles: PUBLIC_ACCESS }
        - { path: ^/2fa/code, roles: PUBLIC_ACCESS }
        - { path: ^/2fa/code/check, roles: PUBLIC_ACCESS }
        - { path: ^/security-capture, roles: PUBLIC_ACCESS }
        - { path: ^/capture-face, roles: PUBLIC_ACCESS }
        # Routes client protégées
        - { path: ^/client/reservation, roles: ROLE_USER }
        - { path: ^/client/mes-reservations, roles: ROLE_USER }
        - { path: ^/client/reservation-detail, roles: ROLE_USER }
        - { path: ^/client/$, roles: ROLE_USER }
        # Routes publiques
        - { path: ^/client/catalogue, roles: PUBLIC_ACCESS }
        - { path: ^/client/planning, roles: PUBLIC_ACCESS }
        - { path: ^/mes-reservations, roles: PUBLIC_ACCESS }
        - { path: ^/logements/recommendations, roles: PUBLIC_ACCESS }
        - { path: ^/logements, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10