services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\CompreFaceService:
        arguments:
            $apiKey: '%env(COMPREFACE_API_KEY)%'
            $baseUrl: '%env(COMPREFACE_BASE_URL)%'

    App\EventListener\TwoFactorLoginListener:
        tags:
            - { name: kernel.event_subscriber }

    App\EventListener\LoginFailureListener:
        tags:
            - { name: kernel.event_subscriber }