parameters:
    brevo.api_key: '%env(BREVO_API_KEY)%'
    openai.api_key: '%env(OPENAI_API_KEY)%'
    openai.model: '%env(OPENAI_MODEL)%'
    stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'
    stripe.secret_key: '%env(STRIPE_SECRET_KEY)%'
    stripe.public_key: '%env(STRIPE_PUBLIC_KEY)%'
    app.base_url: '%env(APP_BASE_URL)%'
    mercure_public_url: '%env(MERCURE_PUBLIC_URL)%'
    gemini.api_key: '%env(GEMINI_API_KEY)%'
    gemini.model: '%env(GEMINI_MODEL)%'


services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $openWeatherApiKey: '%env(OPENWEATHER_API_KEY)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
    App\Service\qrcodeVoyService:
        arguments:
            $appUrl: '%app.base_url%'
    App\Service\CompreFaceService:
        arguments:
            $apiKey: '%env(COMPREFACE_API_KEY)%'
            $baseUrl: '%env(COMPREFACE_BASE_URL)%'

    App\Service\BrevoMailerService:
        arguments:
            $brevoApiKey: '%brevo.api_key%'

    App\Service\OpenAiService:
        arguments:
            $openAiApiKey: '%openai.api_key%'
            $openAiModel: '%openai.model%'

    App\Service\StripeService:
        arguments:
            $stripeSecretKey: '%stripe.secret_key%'

    App\Service\GeminiService:
        arguments:
            $apiKey: '%env(GEMINI_API_KEY)%'
            $logger: '@logger'
            $geminiModel: '%gemini.model%'

    App\Service\AiChatbotService: ~

    App\EventListener\TwoFactorLoginListener:
        tags:
            - { name: kernel.event_subscriber }
    App\Service\PexelsService:
        arguments:
            $pexelsApiKey: '%pexels_api_key%'
    App\EventListener\LoginFailureListener:
        tags:
            - { name: kernel.event_subscriber }
    App\EventListener\LocaleSubscriber:
        tags:
            - { name: kernel.event_subscriber }